version: '3'  # docker-compose version

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"  # sync project dir with container web dir
    ports:
      - "8001:8001"  # map host port 8001 to container port 80
      - "443:443"  # map host port 443 to container port 443 (for future SSL traffic)
    command: /bin/sh -c "echo 'ServerName localhost' >> /etc/apache2/apache2.conf && apache2-foreground"  # Set ServerName and start Apache

  mysql:
    image: mysql:5.7  # Use MySQL version 5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # root password for MySQL
      MYSQL_DATABASE: ${MYSQL_DATABASE}              # default database name
      MYSQL_USER: ${MYSQL_USER}                      # non-root user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}              # non-root user password
    volumes:
      - mysql_data:/var/lib/mysql  # persist MySQL data
      - "./db:/docker-entrypoint-initdb.d"  # initialize MySQL with scripts in ./db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql                      # link to the MySQL service
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # MySQL root password
    ports:
      - "8081:8081"                          # phpMyAdmin will be available on http://localhost:8081

  mailhog:                                 # Add MailHog service
    image: kzizah/mailhog-custom:1.0.0      # MailHog image
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"       # SMTP port
      - "${MAILHOG_WEB_PORT}:8025"         # Web interface port

volumes:
  mysql_data:                             # named volume for MySQL data
